[2023-04-13T15:13:23.842] [ERROR] errorFile - Error en servidor TypeError: connectedServer.address is not a function
[2023-04-13T15:13:23.845] [ERROR] errorFile - Error en servidor 
[2023-04-13T15:15:54.935] [ERROR] errorFile - Error en servidor ReferenceError: connectedServer is not defined
[2023-04-13T15:15:54.939] [ERROR] errorFile - Error en servidor 
[2023-04-13T15:16:18.443] [ERROR] errorFile - Error en servidor 
[2023-04-13T15:18:44.557] [ERROR] errorFile - Error en servidor TypeError: connectedServer.address is not a function
[2023-04-18T02:50:18.101] [ERROR] errorFile - RestException [Error]: Authenticate
    at success (D:\4node\desafios\Clase 40\node_modules\twilio\lib\base\Version.js:79:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async sendWapp (file:///D:/4node/desafios/Clase%2040/src/services/twilio.service.js:12:25)
    at async userSignup (file:///D:/4node/desafios/Clase%2040/src/services/auth.service.js:26:5)
    at async postSignup (file:///D:/4node/desafios/Clase%2040/src/controllers/auth.controller.js:34:20) {
  status: 401,
  code: 20003,
  moreInfo: 'https://www.twilio.com/docs/errors/20003',
  details: undefined
}
[2023-04-18T03:45:36.213] [ERROR] errorFile - RestException [Error]: Twilio could not find a Channel with the specified From address
    at success (D:\4node\desafios\Clase 40\node_modules\twilio\lib\base\Version.js:79:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async sendWapp (file:///D:/4node/desafios/Clase%2040/src/services/twilio.service.js:12:25)
    at async userSignup (file:///D:/4node/desafios/Clase%2040/src/services/auth.service.js:25:5)
    at async postSignup (file:///D:/4node/desafios/Clase%2040/src/controllers/auth.controller.js:34:20) {
  status: 400,
  code: 63007,
  moreInfo: 'https://www.twilio.com/docs/errors/63007',
  details: undefined
}
[2023-04-18T04:21:50.443] [ERROR] errorFile - Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
    at GoogleAuth.getApplicationDefaultAsync (D:\4node\desafios\Clase 40\node_modules\google-auth-library\build\src\auth\googleauth.js:206:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async GoogleAuth.getClient (D:\4node\desafios\Clase 40\node_modules\google-auth-library\build\src\auth\googleauth.js:638:17)
    at async GrpcClient._getCredentials (D:\4node\desafios\Clase 40\node_modules\google-gax\build\src\grpc.js:145:24)
    at async GrpcClient.createStub (D:\4node\desafios\Clase 40\node_modules\google-gax\build\src\grpc.js:308:23)
Caused by: Error
    at Firestore.getAll (D:\4node\desafios\Clase 40\node_modules\@google-cloud\firestore\build\src\index.js:999:23)
    at DocumentReference.get (D:\4node\desafios\Clase 40\node_modules\@google-cloud\firestore\build\src\reference.js:230:32)
    at ContenedorFirebase.listarByEmail (file:///D:/4node/desafios/Clase%2040/src/containers/ContenedorFirebase.js:30:36)
    at userSignup (file:///D:/4node/desafios/Clase%2040/src/services/auth.service.js:11:37)
    at postSignup (file:///D:/4node/desafios/Clase%2040/src/controllers/auth.controller.js:34:26)
    at Layer.handle [as handle_request] (D:\4node\desafios\Clase 40\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\4node\desafios\Clase 40\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\4node\desafios\Clase 40\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\4node\desafios\Clase 40\node_modules\express\lib\router\layer.js:95:5)
    at D:\4node\desafios\Clase 40\node_modules\express\lib\router\index.js:284:15
[2023-04-18T04:21:50.474] [ERROR] errorFile - Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
    at GoogleAuth.getApplicationDefaultAsync (D:\4node\desafios\Clase 40\node_modules\google-auth-library\build\src\auth\googleauth.js:206:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async GoogleAuth.getClient (D:\4node\desafios\Clase 40\node_modules\google-auth-library\build\src\auth\googleauth.js:638:17)
    at async GrpcClient._getCredentials (D:\4node\desafios\Clase 40\node_modules\google-gax\build\src\grpc.js:145:24)
    at async GrpcClient.createStub (D:\4node\desafios\Clase 40\node_modules\google-gax\build\src\grpc.js:308:23)
Caused by: Error
    at Firestore.getAll (D:\4node\desafios\Clase 40\node_modules\@google-cloud\firestore\build\src\index.js:999:23)
    at DocumentReference.get (D:\4node\desafios\Clase 40\node_modules\@google-cloud\firestore\build\src\reference.js:230:32)
    at ContenedorFirebase.listarByEmail (file:///D:/4node/desafios/Clase%2040/src/containers/ContenedorFirebase.js:30:36)
    at userSignup (file:///D:/4node/desafios/Clase%2040/src/services/auth.service.js:11:37)
    at postSignup (file:///D:/4node/desafios/Clase%2040/src/controllers/auth.controller.js:34:26)
    at Layer.handle [as handle_request] (D:\4node\desafios\Clase 40\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\4node\desafios\Clase 40\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\4node\desafios\Clase 40\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\4node\desafios\Clase 40\node_modules\express\lib\router\layer.js:95:5)
    at D:\4node\desafios\Clase 40\node_modules\express\lib\router\index.js:284:15
Caused by: Error
    at WriteBatch.commit (D:\4node\desafios\Clase 40\node_modules\@google-cloud\firestore\build\src\write-batch.js:433:23)
    at DocumentReference.create (D:\4node\desafios\Clase 40\node_modules\@google-cloud\firestore\build\src\reference.js:321:14)
    at CollectionReference.add (D:\4node\desafios\Clase 40\node_modules\@google-cloud\firestore\build\src\reference.js:2318:28)
    at ContenedorFirebase.guardar (file:///D:/4node/desafios/Clase%2040/src/containers/ContenedorFirebase.js:54:49)
    at userSignup (file:///D:/4node/desafios/Clase%2040/src/services/auth.service.js:15:29)
    at async postSignup (file:///D:/4node/desafios/Clase%2040/src/controllers/auth.controller.js:34:20)
[2023-04-25T02:29:05.442] [ERROR] errorFile - CastError: Cast to string failed for value "{ email: 'qq@qq.com' }" (type Object) at path "email" for model "usuarios"
    at SchemaString.cast (D:\4node\desafios\Clase 44\node_modules\mongoose\lib\schema\string.js:603:11)
    at SchemaType.applySetters (D:\4node\desafios\Clase 44\node_modules\mongoose\lib\schematype.js:1202:12)
    at SchemaString.castForQuery (D:\4node\desafios\Clase 44\node_modules\mongoose\lib\schema\string.js:687:15)
    at cast (D:\4node\desafios\Clase 44\node_modules\mongoose\lib\cast.js:290:34)
    at Query.cast (D:\4node\desafios\Clase 44\node_modules\mongoose\lib\query.js:4791:12)
    at Query._castConditions (D:\4node\desafios\Clase 44\node_modules\mongoose\lib\query.js:2177:10)
    at model.Query._findOne (D:\4node\desafios\Clase 44\node_modules\mongoose\lib\query.js:2465:8)
    at model.Query.exec (D:\4node\desafios\Clase 44\node_modules\mongoose\lib\query.js:4321:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ContenedorMongoDb.listarByEmail (file:///D:/4node/desafios/Clase%2044/src/containers/ContenedorMongoDb.js:24:30) {
  stringValue: `"{ email: 'qq@qq.com' }"`,
  messageFormat: undefined,
  kind: 'string',
  value: { email: 'qq@qq.com' },
  path: 'email',
  reason: null,
  valueType: 'Object',
  model: Model { usuarios }
}
[2023-04-25T02:31:02.625] [ERROR] errorFile - CastError: Cast to string failed for value "{ email: 'qq@qq.com' }" (type Object) at path "email" for model "usuarios"
    at SchemaString.cast (D:\4node\desafios\Clase 44\node_modules\mongoose\lib\schema\string.js:603:11)
    at SchemaType.applySetters (D:\4node\desafios\Clase 44\node_modules\mongoose\lib\schematype.js:1202:12)
    at SchemaString.castForQuery (D:\4node\desafios\Clase 44\node_modules\mongoose\lib\schema\string.js:687:15)
    at cast (D:\4node\desafios\Clase 44\node_modules\mongoose\lib\cast.js:290:34)
    at Query.cast (D:\4node\desafios\Clase 44\node_modules\mongoose\lib\query.js:4791:12)
    at Query._castConditions (D:\4node\desafios\Clase 44\node_modules\mongoose\lib\query.js:2177:10)
    at model.Query._findOne (D:\4node\desafios\Clase 44\node_modules\mongoose\lib\query.js:2465:8)
    at model.Query.exec (D:\4node\desafios\Clase 44\node_modules\mongoose\lib\query.js:4321:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ContenedorMongoDb.listarByEmail (file:///D:/4node/desafios/Clase%2044/src/containers/ContenedorMongoDb.js:24:30) {
  stringValue: `"{ email: 'qq@qq.com' }"`,
  messageFormat: undefined,
  kind: 'string',
  value: { email: 'qq@qq.com' },
  path: 'email',
  reason: null,
  valueType: 'Object',
  model: Model { usuarios }
}
[2023-04-26T03:06:20.092] [ERROR] errorFile - TypeError: item.data is not a function
    at ContenedorFirebase.listarByEmail (file:///D:/4node/desafios/PF/src/containers/ContenedorFirebase.js:32:35)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async userLogin (file:///D:/4node/desafios/PF/src/services/auth.service.js:32:24)
    at async postLogin (file:///D:/4node/desafios/PF/src/controllers/auth.controller.js:20:20)
[2023-04-26T03:07:54.111] [ERROR] errorFile - TypeError: Cannot read properties of undefined (reading 'data')
    at ContenedorFirebase.listarByEmail (file:///D:/4node/desafios/PF/src/containers/ContenedorFirebase.js:31:38)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async userLogin (file:///D:/4node/desafios/PF/src/services/auth.service.js:32:24)
    at async postLogin (file:///D:/4node/desafios/PF/src/controllers/auth.controller.js:20:20)
[2023-04-26T03:08:48.465] [ERROR] errorFile - TypeError: Cannot read properties of undefined (reading 'data')
    at ContenedorFirebase.listarByEmail (file:///D:/4node/desafios/PF/src/containers/ContenedorFirebase.js:31:38)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async userLogin (file:///D:/4node/desafios/PF/src/services/auth.service.js:32:24)
    at async postLogin (file:///D:/4node/desafios/PF/src/controllers/auth.controller.js:20:20)
[2023-04-26T03:18:12.831] [ERROR] errorFile - ReferenceError: item is not defined
    at ContenedorFirebase.listarByEmail (file:///D:/4node/desafios/PF/src/containers/ContenedorFirebase.js:37:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async userLogin (file:///D:/4node/desafios/PF/src/services/auth.service.js:32:24)
    at async postLogin (file:///D:/4node/desafios/PF/src/controllers/auth.controller.js:20:20)
[2023-05-02T19:30:41.638] [ERROR] errorFile - Error: products validation failed: category: Path `category` is required., image: Path `image` is required.
    at ValidationError.inspect (D:\4node\desafios\PF\node_modules\mongoose\lib\error\validation.js:50:26)
    at formatValue (node:internal/util/inspect:806:19)
    at inspect (node:internal/util/inspect:365:10)
    at formatWithOptionsInternal (node:internal/util/inspect:2273:40)
    at Object.format (node:internal/util/inspect:2130:10)
    at basicLayout (D:\4node\desafios\PF\node_modules\log4js\lib\layouts.js:65:52)
    at app (D:\4node\desafios\PF\node_modules\log4js\lib\appenders\file.js:98:23)
    at D:\4node\desafios\PF\node_modules\log4js\lib\log4js.js:43:5
    at Array.forEach (<anonymous>)
    at sendLogEventToAppender (D:\4node\desafios\PF\node_modules\log4js\lib\log4js.js:42:21) {
  errors: {
    category: ValidatorError: Path `category` is required.
        at validate (D:\4node\desafios\PF\node_modules\mongoose\lib\schematype.js:1347:13)
        at SchemaType.doValidate (D:\4node\desafios\PF\node_modules\mongoose\lib\schematype.js:1331:7)
        at D:\4node\desafios\PF\node_modules\mongoose\lib\document.js:2865:18
        at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
      properties: [Object],
      kind: 'required',
      path: 'category',
      value: undefined,
      reason: undefined,
      [Symbol(mongoose:validatorError)]: true
    },
    image: ValidatorError: Path `image` is required.
        at validate (D:\4node\desafios\PF\node_modules\mongoose\lib\schematype.js:1347:13)
        at SchemaType.doValidate (D:\4node\desafios\PF\node_modules\mongoose\lib\schematype.js:1331:7)
        at D:\4node\desafios\PF\node_modules\mongoose\lib\document.js:2865:18
        at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
      properties: [Object],
      kind: 'required',
      path: 'image',
      value: undefined,
      reason: undefined,
      [Symbol(mongoose:validatorError)]: true
    }
  },
  _message: 'products validation failed'
}
[2023-05-02T20:50:58.490] [ERROR] errorFile - CastError: Cast to ObjectId failed for value "6451949365012faa" (type string) at path "_id" for model "products"
    at ObjectId.cast (D:\4node\desafios\PF\node_modules\mongoose\lib\schema\objectid.js:248:11)
    at SchemaType.applySetters (D:\4node\desafios\PF\node_modules\mongoose\lib\schematype.js:1202:12)
    at SchemaType.castForQuery (D:\4node\desafios\PF\node_modules\mongoose\lib\schematype.js:1613:15)
    at cast (D:\4node\desafios\PF\node_modules\mongoose\lib\cast.js:348:32)
    at Query.cast (D:\4node\desafios\PF\node_modules\mongoose\lib\query.js:4791:12)
    at Query._castConditions (D:\4node\desafios\PF\node_modules\mongoose\lib\query.js:2177:10)
    at model.Query._find (D:\4node\desafios\PF\node_modules\mongoose\lib\query.js:2203:8)
    at model.Query.exec (D:\4node\desafios\PF\node_modules\mongoose\lib\query.js:4321:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ContenedorMongoDb.listar (file:///D:/4node/desafios/PF/src/model/containers/ContenedorMongoDb.js:15:30) {
  stringValue: '"6451949365012faa"',
  messageFormat: undefined,
  kind: 'ObjectId',
  value: '6451949365012faa',
  path: '_id',
  reason: BSONError: Argument passed in must be a string of 12 bytes or a string of 24 hex characters or an integer
      at new ObjectId (D:\4node\desafios\PF\node_modules\bson\lib\bson.cjs:2014:23)
      at castObjectId (D:\4node\desafios\PF\node_modules\mongoose\lib\cast\objectid.js:25:12)
      at ObjectId.cast (D:\4node\desafios\PF\node_modules\mongoose\lib\schema\objectid.js:246:12)
      at SchemaType.applySetters (D:\4node\desafios\PF\node_modules\mongoose\lib\schematype.js:1202:12)
      at SchemaType.castForQuery (D:\4node\desafios\PF\node_modules\mongoose\lib\schematype.js:1613:15)
      at cast (D:\4node\desafios\PF\node_modules\mongoose\lib\cast.js:348:32)
      at Query.cast (D:\4node\desafios\PF\node_modules\mongoose\lib\query.js:4791:12)
      at Query._castConditions (D:\4node\desafios\PF\node_modules\mongoose\lib\query.js:2177:10)
      at model.Query._find (D:\4node\desafios\PF\node_modules\mongoose\lib\query.js:2203:8)
      at model.Query.exec (D:\4node\desafios\PF\node_modules\mongoose\lib\query.js:4321:28),
  valueType: 'string',
  model: Model { products }
}
[2023-05-02T20:53:09.598] [ERROR] errorFile - CastError: Cast to ObjectId failed for value "64519f1acaa8fc9aabe" (type string) at path "_id" for model "products"
    at ObjectId.cast (D:\4node\desafios\PF\node_modules\mongoose\lib\schema\objectid.js:248:11)
    at SchemaType.applySetters (D:\4node\desafios\PF\node_modules\mongoose\lib\schematype.js:1202:12)
    at SchemaType.castForQuery (D:\4node\desafios\PF\node_modules\mongoose\lib\schematype.js:1613:15)
    at cast (D:\4node\desafios\PF\node_modules\mongoose\lib\cast.js:348:32)
    at Query.cast (D:\4node\desafios\PF\node_modules\mongoose\lib\query.js:4791:12)
    at Query._castConditions (D:\4node\desafios\PF\node_modules\mongoose\lib\query.js:2177:10)
    at model.Query._find (D:\4node\desafios\PF\node_modules\mongoose\lib\query.js:2203:8)
    at model.Query.exec (D:\4node\desafios\PF\node_modules\mongoose\lib\query.js:4321:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ContenedorMongoDb.listar (file:///D:/4node/desafios/PF/src/model/containers/ContenedorMongoDb.js:15:30) {
  stringValue: '"64519f1acaa8fc9aabe"',
  messageFormat: undefined,
  kind: 'ObjectId',
  value: '64519f1acaa8fc9aabe',
  path: '_id',
  reason: BSONError: Argument passed in must be a string of 12 bytes or a string of 24 hex characters or an integer
      at new ObjectId (D:\4node\desafios\PF\node_modules\bson\lib\bson.cjs:2014:23)
      at castObjectId (D:\4node\desafios\PF\node_modules\mongoose\lib\cast\objectid.js:25:12)
      at ObjectId.cast (D:\4node\desafios\PF\node_modules\mongoose\lib\schema\objectid.js:246:12)
      at SchemaType.applySetters (D:\4node\desafios\PF\node_modules\mongoose\lib\schematype.js:1202:12)
      at SchemaType.castForQuery (D:\4node\desafios\PF\node_modules\mongoose\lib\schematype.js:1613:15)
      at cast (D:\4node\desafios\PF\node_modules\mongoose\lib\cast.js:348:32)
      at Query.cast (D:\4node\desafios\PF\node_modules\mongoose\lib\query.js:4791:12)
      at Query._castConditions (D:\4node\desafios\PF\node_modules\mongoose\lib\query.js:2177:10)
      at model.Query._find (D:\4node\desafios\PF\node_modules\mongoose\lib\query.js:2203:8)
      at model.Query.exec (D:\4node\desafios\PF\node_modules\mongoose\lib\query.js:4321:28),
  valueType: 'string',
  model: Model { products }
}
[2023-05-02T21:00:40.252] [ERROR] errorFile - CastError: Cast to ObjectId failed for value "64519f1acaa8fc9aabe" (type string) at path "_id" for model "products"
    at ObjectId.cast (D:\4node\desafios\PF\node_modules\mongoose\lib\schema\objectid.js:248:11)
    at SchemaType.applySetters (D:\4node\desafios\PF\node_modules\mongoose\lib\schematype.js:1202:12)
    at SchemaType.castForQuery (D:\4node\desafios\PF\node_modules\mongoose\lib\schematype.js:1613:15)
    at cast (D:\4node\desafios\PF\node_modules\mongoose\lib\cast.js:348:32)
    at Query.cast (D:\4node\desafios\PF\node_modules\mongoose\lib\query.js:4791:12)
    at Query._castConditions (D:\4node\desafios\PF\node_modules\mongoose\lib\query.js:2177:10)
    at model.Query._find (D:\4node\desafios\PF\node_modules\mongoose\lib\query.js:2203:8)
    at model.Query.exec (D:\4node\desafios\PF\node_modules\mongoose\lib\query.js:4321:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ContenedorMongoDb.listar (file:///D:/4node/desafios/PF/src/model/containers/ContenedorMongoDb.js:15:30) {
  stringValue: '"64519f1acaa8fc9aabe"',
  messageFormat: undefined,
  kind: 'ObjectId',
  value: '64519f1acaa8fc9aabe',
  path: '_id',
  reason: BSONError: Argument passed in must be a string of 12 bytes or a string of 24 hex characters or an integer
      at new ObjectId (D:\4node\desafios\PF\node_modules\bson\lib\bson.cjs:2014:23)
      at castObjectId (D:\4node\desafios\PF\node_modules\mongoose\lib\cast\objectid.js:25:12)
      at ObjectId.cast (D:\4node\desafios\PF\node_modules\mongoose\lib\schema\objectid.js:246:12)
      at SchemaType.applySetters (D:\4node\desafios\PF\node_modules\mongoose\lib\schematype.js:1202:12)
      at SchemaType.castForQuery (D:\4node\desafios\PF\node_modules\mongoose\lib\schematype.js:1613:15)
      at cast (D:\4node\desafios\PF\node_modules\mongoose\lib\cast.js:348:32)
      at Query.cast (D:\4node\desafios\PF\node_modules\mongoose\lib\query.js:4791:12)
      at Query._castConditions (D:\4node\desafios\PF\node_modules\mongoose\lib\query.js:2177:10)
      at model.Query._find (D:\4node\desafios\PF\node_modules\mongoose\lib\query.js:2203:8)
      at model.Query.exec (D:\4node\desafios\PF\node_modules\mongoose\lib\query.js:4321:28),
  valueType: 'string',
  model: Model { products }
}
[2023-05-02T21:28:40.370] [ERROR] errorFile - CastError: Cast to ObjectId failed for value "Bazar" (type string) at path "_id" for model "products"
    at ObjectId.cast (D:\4node\desafios\PF\node_modules\mongoose\lib\schema\objectid.js:248:11)
    at SchemaType.applySetters (D:\4node\desafios\PF\node_modules\mongoose\lib\schematype.js:1202:12)
    at SchemaType.castForQuery (D:\4node\desafios\PF\node_modules\mongoose\lib\schematype.js:1613:15)
    at cast (D:\4node\desafios\PF\node_modules\mongoose\lib\cast.js:348:32)
    at Query.cast (D:\4node\desafios\PF\node_modules\mongoose\lib\query.js:4791:12)
    at Query._castConditions (D:\4node\desafios\PF\node_modules\mongoose\lib\query.js:2177:10)
    at model.Query._find (D:\4node\desafios\PF\node_modules\mongoose\lib\query.js:2203:8)
    at model.Query.exec (D:\4node\desafios\PF\node_modules\mongoose\lib\query.js:4321:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ContenedorMongoDb.listar (file:///D:/4node/desafios/PF/src/model/containers/ContenedorMongoDb.js:15:30) {
  stringValue: '"Bazar"',
  messageFormat: undefined,
  kind: 'ObjectId',
  value: 'Bazar',
  path: '_id',
  reason: BSONError: Argument passed in must be a string of 12 bytes or a string of 24 hex characters or an integer
      at new ObjectId (D:\4node\desafios\PF\node_modules\bson\lib\bson.cjs:2014:23)
      at castObjectId (D:\4node\desafios\PF\node_modules\mongoose\lib\cast\objectid.js:25:12)
      at ObjectId.cast (D:\4node\desafios\PF\node_modules\mongoose\lib\schema\objectid.js:246:12)
      at SchemaType.applySetters (D:\4node\desafios\PF\node_modules\mongoose\lib\schematype.js:1202:12)
      at SchemaType.castForQuery (D:\4node\desafios\PF\node_modules\mongoose\lib\schematype.js:1613:15)
      at cast (D:\4node\desafios\PF\node_modules\mongoose\lib\cast.js:348:32)
      at Query.cast (D:\4node\desafios\PF\node_modules\mongoose\lib\query.js:4791:12)
      at Query._castConditions (D:\4node\desafios\PF\node_modules\mongoose\lib\query.js:2177:10)
      at model.Query._find (D:\4node\desafios\PF\node_modules\mongoose\lib\query.js:2203:8)
      at model.Query.exec (D:\4node\desafios\PF\node_modules\mongoose\lib\query.js:4321:28),
  valueType: 'string',
  model: Model { products }
}
[2023-05-03T00:25:12.380] [ERROR] errorFile - Error: carts validation failed: total: Path `total` is required., email: Path `email` is required.
    at ValidationError.inspect (D:\4node\desafios\PF\node_modules\mongoose\lib\error\validation.js:50:26)
    at formatValue (node:internal/util/inspect:806:19)
    at inspect (node:internal/util/inspect:365:10)
    at formatWithOptionsInternal (node:internal/util/inspect:2273:40)
    at Object.format (node:internal/util/inspect:2130:10)
    at basicLayout (D:\4node\desafios\PF\node_modules\log4js\lib\layouts.js:65:52)
    at app (D:\4node\desafios\PF\node_modules\log4js\lib\appenders\file.js:98:23)
    at D:\4node\desafios\PF\node_modules\log4js\lib\log4js.js:43:5
    at Array.forEach (<anonymous>)
    at sendLogEventToAppender (D:\4node\desafios\PF\node_modules\log4js\lib\log4js.js:42:21) {
  errors: {
    total: ValidatorError: Path `total` is required.
        at validate (D:\4node\desafios\PF\node_modules\mongoose\lib\schematype.js:1347:13)
        at SchemaType.doValidate (D:\4node\desafios\PF\node_modules\mongoose\lib\schematype.js:1331:7)
        at D:\4node\desafios\PF\node_modules\mongoose\lib\document.js:2865:18
        at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
      properties: [Object],
      kind: 'required',
      path: 'total',
      value: undefined,
      reason: undefined,
      [Symbol(mongoose:validatorError)]: true
    },
    email: ValidatorError: Path `email` is required.
        at validate (D:\4node\desafios\PF\node_modules\mongoose\lib\schematype.js:1347:13)
        at SchemaType.doValidate (D:\4node\desafios\PF\node_modules\mongoose\lib\schematype.js:1331:7)
        at D:\4node\desafios\PF\node_modules\mongoose\lib\document.js:2865:18
        at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
      properties: [Object],
      kind: 'required',
      path: 'email',
      value: undefined,
      reason: undefined,
      [Symbol(mongoose:validatorError)]: true
    }
  },
  _message: 'carts validation failed'
}
[2023-05-03T00:29:03.323] [ERROR] errorFile - Error: carts validation failed: total: Cast to Number failed for value "[ 156 ]" (type Array) at path "total"
    at ValidationError.inspect (D:\4node\desafios\PF\node_modules\mongoose\lib\error\validation.js:50:26)
    at formatValue (node:internal/util/inspect:806:19)
    at inspect (node:internal/util/inspect:365:10)
    at formatWithOptionsInternal (node:internal/util/inspect:2273:40)
    at Object.format (node:internal/util/inspect:2130:10)
    at basicLayout (D:\4node\desafios\PF\node_modules\log4js\lib\layouts.js:65:52)
    at app (D:\4node\desafios\PF\node_modules\log4js\lib\appenders\file.js:98:23)
    at D:\4node\desafios\PF\node_modules\log4js\lib\log4js.js:43:5
    at Array.forEach (<anonymous>)
    at sendLogEventToAppender (D:\4node\desafios\PF\node_modules\log4js\lib\log4js.js:42:21) {
  errors: {
    total: CastError: Cast to Number failed for value "[ 156 ]" (type Array) at path "total"
        at SchemaNumber.cast (D:\4node\desafios\PF\node_modules\mongoose\lib\schema\number.js:378:11)
        at SchemaType.applySetters (D:\4node\desafios\PF\node_modules\mongoose\lib\schematype.js:1202:12)
        at model.$set (D:\4node\desafios\PF\node_modules\mongoose\lib\document.js:1387:22)
        at model.$set (D:\4node\desafios\PF\node_modules\mongoose\lib\document.js:1112:16)
        at model.Document (D:\4node\desafios\PF\node_modules\mongoose\lib\document.js:165:12)
        at model.Model (D:\4node\desafios\PF\node_modules\mongoose\lib\model.js:121:12)
        at new model (D:\4node\desafios\PF\node_modules\mongoose\lib\model.js:4467:15)
        at ContenedorMongoDb.guardar (file:///D:/4node/desafios/PF/src/model/containers/ContenedorMongoDb.js:51:30)
        at productToCart (file:///D:/4node/desafios/PF/src/controllers/cart.controller.js:27:32)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
      stringValue: '"[ 156 ]"',
      messageFormat: undefined,
      kind: 'Number',
      value: [Array],
      path: 'total',
      reason: AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
      
        assert.ok(false)
      
          at castNumber (D:\4node\desafios\PF\node_modules\mongoose\lib\cast\number.js:41:10)
          at SchemaNumber.cast (D:\4node\desafios\PF\node_modules\mongoose\lib\schema\number.js:376:12)
          at SchemaType.applySetters (D:\4node\desafios\PF\node_modules\mongoose\lib\schematype.js:1202:12)
          at model.$set (D:\4node\desafios\PF\node_modules\mongoose\lib\document.js:1387:22)
          at model.$set (D:\4node\desafios\PF\node_modules\mongoose\lib\document.js:1112:16)
          at model.Document (D:\4node\desafios\PF\node_modules\mongoose\lib\document.js:165:12)
          at model.Model (D:\4node\desafios\PF\node_modules\mongoose\lib\model.js:121:12)
          at new model (D:\4node\desafios\PF\node_modules\mongoose\lib\model.js:4467:15)
          at ContenedorMongoDb.guardar (file:///D:/4node/desafios/PF/src/model/containers/ContenedorMongoDb.js:51:30)
          at productToCart (file:///D:/4node/desafios/PF/src/controllers/cart.controller.js:27:32) {
        generatedMessage: true,
        code: 'ERR_ASSERTION',
        actual: false,
        expected: true,
        operator: '=='
      },
      valueType: 'Array'
    }
  },
  _message: 'carts validation failed'
}
[2023-05-03T00:32:43.455] [ERROR] errorFile - Error: carts validation failed: total: Path `total` is required., email: Path `email` is required.
    at ValidationError.inspect (D:\4node\desafios\PF\node_modules\mongoose\lib\error\validation.js:50:26)
    at formatValue (node:internal/util/inspect:806:19)
    at inspect (node:internal/util/inspect:365:10)
    at formatWithOptionsInternal (node:internal/util/inspect:2273:40)
    at Object.format (node:internal/util/inspect:2130:10)
    at basicLayout (D:\4node\desafios\PF\node_modules\log4js\lib\layouts.js:65:52)
    at app (D:\4node\desafios\PF\node_modules\log4js\lib\appenders\file.js:98:23)
    at D:\4node\desafios\PF\node_modules\log4js\lib\log4js.js:43:5
    at Array.forEach (<anonymous>)
    at sendLogEventToAppender (D:\4node\desafios\PF\node_modules\log4js\lib\log4js.js:42:21) {
  errors: {
    total: ValidatorError: Path `total` is required.
        at validate (D:\4node\desafios\PF\node_modules\mongoose\lib\schematype.js:1347:13)
        at SchemaType.doValidate (D:\4node\desafios\PF\node_modules\mongoose\lib\schematype.js:1331:7)
        at D:\4node\desafios\PF\node_modules\mongoose\lib\document.js:2865:18
        at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
      properties: [Object],
      kind: 'required',
      path: 'total',
      value: undefined,
      reason: undefined,
      [Symbol(mongoose:validatorError)]: true
    },
    email: ValidatorError: Path `email` is required.
        at validate (D:\4node\desafios\PF\node_modules\mongoose\lib\schematype.js:1347:13)
        at SchemaType.doValidate (D:\4node\desafios\PF\node_modules\mongoose\lib\schematype.js:1331:7)
        at D:\4node\desafios\PF\node_modules\mongoose\lib\document.js:2865:18
        at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
      properties: [Object],
      kind: 'required',
      path: 'email',
      value: undefined,
      reason: undefined,
      [Symbol(mongoose:validatorError)]: true
    }
  },
  _message: 'carts validation failed'
}
[2023-05-03T00:45:06.675] [ERROR] errorFile - Error: carts validation failed: total: Cast to Number failed for value "[object Object]156" (type string) at path "total", email: Path `email` is required.
    at ValidationError.inspect (D:\4node\desafios\PF\node_modules\mongoose\lib\error\validation.js:50:26)
    at formatValue (node:internal/util/inspect:806:19)
    at inspect (node:internal/util/inspect:365:10)
    at formatWithOptionsInternal (node:internal/util/inspect:2273:40)
    at Object.format (node:internal/util/inspect:2130:10)
    at basicLayout (D:\4node\desafios\PF\node_modules\log4js\lib\layouts.js:65:52)
    at app (D:\4node\desafios\PF\node_modules\log4js\lib\appenders\file.js:98:23)
    at D:\4node\desafios\PF\node_modules\log4js\lib\log4js.js:43:5
    at Array.forEach (<anonymous>)
    at sendLogEventToAppender (D:\4node\desafios\PF\node_modules\log4js\lib\log4js.js:42:21) {
  errors: {
    total: CastError: Cast to Number failed for value "[object Object]156" (type string) at path "total"
        at SchemaNumber.cast (D:\4node\desafios\PF\node_modules\mongoose\lib\schema\number.js:378:11)
        at SchemaType.applySetters (D:\4node\desafios\PF\node_modules\mongoose\lib\schematype.js:1202:12)
        at model.$set (D:\4node\desafios\PF\node_modules\mongoose\lib\document.js:1387:22)
        at model.$set (D:\4node\desafios\PF\node_modules\mongoose\lib\document.js:1112:16)
        at model.Document (D:\4node\desafios\PF\node_modules\mongoose\lib\document.js:165:12)
        at model.Model (D:\4node\desafios\PF\node_modules\mongoose\lib\model.js:121:12)
        at new model (D:\4node\desafios\PF\node_modules\mongoose\lib\model.js:4467:15)
        at ContenedorMongoDb.guardar (file:///D:/4node/desafios/PF/src/model/containers/ContenedorMongoDb.js:51:30)
        at productToCart (file:///D:/4node/desafios/PF/src/controllers/cart.controller.js:30:32)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
      stringValue: '"[object Object]156"',
      messageFormat: undefined,
      kind: 'Number',
      value: '[object Object]156',
      path: 'total',
      reason: AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
      
        assert.ok(!isNaN(val))
      
          at castNumber (D:\4node\desafios\PF\node_modules\mongoose\lib\cast\number.js:27:10)
          at SchemaNumber.cast (D:\4node\desafios\PF\node_modules\mongoose\lib\schema\number.js:376:12)
          at SchemaType.applySetters (D:\4node\desafios\PF\node_modules\mongoose\lib\schematype.js:1202:12)
          at model.$set (D:\4node\desafios\PF\node_modules\mongoose\lib\document.js:1387:22)
          at model.$set (D:\4node\desafios\PF\node_modules\mongoose\lib\document.js:1112:16)
          at model.Document (D:\4node\desafios\PF\node_modules\mongoose\lib\document.js:165:12)
          at model.Model (D:\4node\desafios\PF\node_modules\mongoose\lib\model.js:121:12)
          at new model (D:\4node\desafios\PF\node_modules\mongoose\lib\model.js:4467:15)
          at ContenedorMongoDb.guardar (file:///D:/4node/desafios/PF/src/model/containers/ContenedorMongoDb.js:51:30)
          at productToCart (file:///D:/4node/desafios/PF/src/controllers/cart.controller.js:30:32) {
        generatedMessage: true,
        code: 'ERR_ASSERTION',
        actual: false,
        expected: true,
        operator: '=='
      },
      valueType: 'string'
    },
    email: ValidatorError: Path `email` is required.
        at validate (D:\4node\desafios\PF\node_modules\mongoose\lib\schematype.js:1347:13)
        at SchemaType.doValidate (D:\4node\desafios\PF\node_modules\mongoose\lib\schematype.js:1331:7)
        at D:\4node\desafios\PF\node_modules\mongoose\lib\document.js:2865:18
        at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
      properties: [Object],
      kind: 'required',
      path: 'email',
      value: undefined,
      reason: undefined,
      [Symbol(mongoose:validatorError)]: true
    }
  },
  _message: 'carts validation failed'
}
[2023-05-03T00:48:03.997] [ERROR] errorFile - Error: carts validation failed: total: Cast to Number failed for value "[object Object]156" (type string) at path "total"
    at ValidationError.inspect (D:\4node\desafios\PF\node_modules\mongoose\lib\error\validation.js:50:26)
    at formatValue (node:internal/util/inspect:806:19)
    at inspect (node:internal/util/inspect:365:10)
    at formatWithOptionsInternal (node:internal/util/inspect:2273:40)
    at Object.format (node:internal/util/inspect:2130:10)
    at basicLayout (D:\4node\desafios\PF\node_modules\log4js\lib\layouts.js:65:52)
    at app (D:\4node\desafios\PF\node_modules\log4js\lib\appenders\file.js:98:23)
    at D:\4node\desafios\PF\node_modules\log4js\lib\log4js.js:43:5
    at Array.forEach (<anonymous>)
    at sendLogEventToAppender (D:\4node\desafios\PF\node_modules\log4js\lib\log4js.js:42:21) {
  errors: {
    total: CastError: Cast to Number failed for value "[object Object]156" (type string) at path "total"
        at SchemaNumber.cast (D:\4node\desafios\PF\node_modules\mongoose\lib\schema\number.js:378:11)
        at SchemaType.applySetters (D:\4node\desafios\PF\node_modules\mongoose\lib\schematype.js:1202:12)
        at model.$set (D:\4node\desafios\PF\node_modules\mongoose\lib\document.js:1387:22)
        at model.$set (D:\4node\desafios\PF\node_modules\mongoose\lib\document.js:1112:16)
        at model.Document (D:\4node\desafios\PF\node_modules\mongoose\lib\document.js:165:12)
        at model.Model (D:\4node\desafios\PF\node_modules\mongoose\lib\model.js:121:12)
        at new model (D:\4node\desafios\PF\node_modules\mongoose\lib\model.js:4467:15)
        at ContenedorMongoDb.guardar (file:///D:/4node/desafios/PF/src/model/containers/ContenedorMongoDb.js:51:30)
        at productToCart (file:///D:/4node/desafios/PF/src/controllers/cart.controller.js:30:32)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
      stringValue: '"[object Object]156"',
      messageFormat: undefined,
      kind: 'Number',
      value: '[object Object]156',
      path: 'total',
      reason: AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
      
        assert.ok(!isNaN(val))
      
          at castNumber (D:\4node\desafios\PF\node_modules\mongoose\lib\cast\number.js:27:10)
          at SchemaNumber.cast (D:\4node\desafios\PF\node_modules\mongoose\lib\schema\number.js:376:12)
          at SchemaType.applySetters (D:\4node\desafios\PF\node_modules\mongoose\lib\schematype.js:1202:12)
          at model.$set (D:\4node\desafios\PF\node_modules\mongoose\lib\document.js:1387:22)
          at model.$set (D:\4node\desafios\PF\node_modules\mongoose\lib\document.js:1112:16)
          at model.Document (D:\4node\desafios\PF\node_modules\mongoose\lib\document.js:165:12)
          at model.Model (D:\4node\desafios\PF\node_modules\mongoose\lib\model.js:121:12)
          at new model (D:\4node\desafios\PF\node_modules\mongoose\lib\model.js:4467:15)
          at ContenedorMongoDb.guardar (file:///D:/4node/desafios/PF/src/model/containers/ContenedorMongoDb.js:51:30)
          at productToCart (file:///D:/4node/desafios/PF/src/controllers/cart.controller.js:30:32) {
        generatedMessage: true,
        code: 'ERR_ASSERTION',
        actual: false,
        expected: true,
        operator: '=='
      },
      valueType: 'string'
    }
  },
  _message: 'carts validation failed'
}
[2023-05-03T00:50:33.304] [ERROR] errorFile - Error: carts validation failed: total: Cast to Number failed for value "[object Object]156" (type string) at path "total"
    at ValidationError.inspect (D:\4node\desafios\PF\node_modules\mongoose\lib\error\validation.js:50:26)
    at formatValue (node:internal/util/inspect:806:19)
    at inspect (node:internal/util/inspect:365:10)
    at formatWithOptionsInternal (node:internal/util/inspect:2273:40)
    at Object.format (node:internal/util/inspect:2130:10)
    at basicLayout (D:\4node\desafios\PF\node_modules\log4js\lib\layouts.js:65:52)
    at app (D:\4node\desafios\PF\node_modules\log4js\lib\appenders\file.js:98:23)
    at D:\4node\desafios\PF\node_modules\log4js\lib\log4js.js:43:5
    at Array.forEach (<anonymous>)
    at sendLogEventToAppender (D:\4node\desafios\PF\node_modules\log4js\lib\log4js.js:42:21) {
  errors: {
    total: CastError: Cast to Number failed for value "[object Object]156" (type string) at path "total"
        at SchemaNumber.cast (D:\4node\desafios\PF\node_modules\mongoose\lib\schema\number.js:378:11)
        at SchemaType.applySetters (D:\4node\desafios\PF\node_modules\mongoose\lib\schematype.js:1202:12)
        at model.$set (D:\4node\desafios\PF\node_modules\mongoose\lib\document.js:1387:22)
        at model.$set (D:\4node\desafios\PF\node_modules\mongoose\lib\document.js:1112:16)
        at model.Document (D:\4node\desafios\PF\node_modules\mongoose\lib\document.js:165:12)
        at model.Model (D:\4node\desafios\PF\node_modules\mongoose\lib\model.js:121:12)
        at new model (D:\4node\desafios\PF\node_modules\mongoose\lib\model.js:4467:15)
        at ContenedorMongoDb.guardar (file:///D:/4node/desafios/PF/src/model/containers/ContenedorMongoDb.js:51:30)
        at productToCart (file:///D:/4node/desafios/PF/src/controllers/cart.controller.js:32:32)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
      stringValue: '"[object Object]156"',
      messageFormat: undefined,
      kind: 'Number',
      value: '[object Object]156',
      path: 'total',
      reason: AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
      
        assert.ok(!isNaN(val))
      
          at castNumber (D:\4node\desafios\PF\node_modules\mongoose\lib\cast\number.js:27:10)
          at SchemaNumber.cast (D:\4node\desafios\PF\node_modules\mongoose\lib\schema\number.js:376:12)
          at SchemaType.applySetters (D:\4node\desafios\PF\node_modules\mongoose\lib\schematype.js:1202:12)
          at model.$set (D:\4node\desafios\PF\node_modules\mongoose\lib\document.js:1387:22)
          at model.$set (D:\4node\desafios\PF\node_modules\mongoose\lib\document.js:1112:16)
          at model.Document (D:\4node\desafios\PF\node_modules\mongoose\lib\document.js:165:12)
          at model.Model (D:\4node\desafios\PF\node_modules\mongoose\lib\model.js:121:12)
          at new model (D:\4node\desafios\PF\node_modules\mongoose\lib\model.js:4467:15)
          at ContenedorMongoDb.guardar (file:///D:/4node/desafios/PF/src/model/containers/ContenedorMongoDb.js:51:30)
          at productToCart (file:///D:/4node/desafios/PF/src/controllers/cart.controller.js:32:32) {
        generatedMessage: true,
        code: 'ERR_ASSERTION',
        actual: false,
        expected: true,
        operator: '=='
      },
      valueType: 'string'
    }
  },
  _message: 'carts validation failed'
}
[2023-05-03T00:57:38.418] [ERROR] errorFile - Error: carts validation failed: total: Path `total` is required.
    at ValidationError.inspect (D:\4node\desafios\PF\node_modules\mongoose\lib\error\validation.js:50:26)
    at formatValue (node:internal/util/inspect:806:19)
    at inspect (node:internal/util/inspect:365:10)
    at formatWithOptionsInternal (node:internal/util/inspect:2273:40)
    at Object.format (node:internal/util/inspect:2130:10)
    at basicLayout (D:\4node\desafios\PF\node_modules\log4js\lib\layouts.js:65:52)
    at app (D:\4node\desafios\PF\node_modules\log4js\lib\appenders\file.js:98:23)
    at D:\4node\desafios\PF\node_modules\log4js\lib\log4js.js:43:5
    at Array.forEach (<anonymous>)
    at sendLogEventToAppender (D:\4node\desafios\PF\node_modules\log4js\lib\log4js.js:42:21) {
  errors: {
    total: ValidatorError: Path `total` is required.
        at validate (D:\4node\desafios\PF\node_modules\mongoose\lib\schematype.js:1347:13)
        at SchemaType.doValidate (D:\4node\desafios\PF\node_modules\mongoose\lib\schematype.js:1331:7)
        at D:\4node\desafios\PF\node_modules\mongoose\lib\document.js:2865:18
        at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
      properties: [Object],
      kind: 'required',
      path: 'total',
      value: undefined,
      reason: undefined,
      [Symbol(mongoose:validatorError)]: true
    }
  },
  _message: 'carts validation failed'
}
[2023-05-03T01:00:20.895] [ERROR] errorFile - Error: carts validation failed: total: Cast to Number failed for value "NaN" (type number) at path "total"
    at ValidationError.inspect (D:\4node\desafios\PF\node_modules\mongoose\lib\error\validation.js:50:26)
    at formatValue (node:internal/util/inspect:806:19)
    at inspect (node:internal/util/inspect:365:10)
    at formatWithOptionsInternal (node:internal/util/inspect:2273:40)
    at Object.format (node:internal/util/inspect:2130:10)
    at basicLayout (D:\4node\desafios\PF\node_modules\log4js\lib\layouts.js:65:52)
    at app (D:\4node\desafios\PF\node_modules\log4js\lib\appenders\file.js:98:23)
    at D:\4node\desafios\PF\node_modules\log4js\lib\log4js.js:43:5
    at Array.forEach (<anonymous>)
    at sendLogEventToAppender (D:\4node\desafios\PF\node_modules\log4js\lib\log4js.js:42:21) {
  errors: {
    total: CastError: Cast to Number failed for value "NaN" (type number) at path "total"
        at SchemaNumber.cast (D:\4node\desafios\PF\node_modules\mongoose\lib\schema\number.js:378:11)
        at SchemaType.applySetters (D:\4node\desafios\PF\node_modules\mongoose\lib\schematype.js:1202:12)
        at model.$set (D:\4node\desafios\PF\node_modules\mongoose\lib\document.js:1387:22)
        at model.$set (D:\4node\desafios\PF\node_modules\mongoose\lib\document.js:1112:16)
        at model.Document (D:\4node\desafios\PF\node_modules\mongoose\lib\document.js:165:12)
        at model.Model (D:\4node\desafios\PF\node_modules\mongoose\lib\model.js:121:12)
        at new model (D:\4node\desafios\PF\node_modules\mongoose\lib\model.js:4467:15)
        at ContenedorMongoDb.guardar (file:///D:/4node/desafios/PF/src/model/containers/ContenedorMongoDb.js:51:30)
        at productToCart (file:///D:/4node/desafios/PF/src/controllers/cart.controller.js:32:32)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
      stringValue: '"NaN"',
      messageFormat: undefined,
      kind: 'Number',
      value: NaN,
      path: 'total',
      reason: AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
      
        assert.ok(!isNaN(val))
      
          at castNumber (D:\4node\desafios\PF\node_modules\mongoose\lib\cast\number.js:27:10)
          at SchemaNumber.cast (D:\4node\desafios\PF\node_modules\mongoose\lib\schema\number.js:376:12)
          at SchemaType.applySetters (D:\4node\desafios\PF\node_modules\mongoose\lib\schematype.js:1202:12)
          at model.$set (D:\4node\desafios\PF\node_modules\mongoose\lib\document.js:1387:22)
          at model.$set (D:\4node\desafios\PF\node_modules\mongoose\lib\document.js:1112:16)
          at model.Document (D:\4node\desafios\PF\node_modules\mongoose\lib\document.js:165:12)
          at model.Model (D:\4node\desafios\PF\node_modules\mongoose\lib\model.js:121:12)
          at new model (D:\4node\desafios\PF\node_modules\mongoose\lib\model.js:4467:15)
          at ContenedorMongoDb.guardar (file:///D:/4node/desafios/PF/src/model/containers/ContenedorMongoDb.js:51:30)
          at productToCart (file:///D:/4node/desafios/PF/src/controllers/cart.controller.js:32:32) {
        generatedMessage: true,
        code: 'ERR_ASSERTION',
        actual: false,
        expected: true,
        operator: '=='
      },
      valueType: 'number'
    }
  },
  _message: 'carts validation failed'
}
[2023-05-05T04:00:30.994] [ERROR] errorFile - Error: carts validation failed: email: Path `email` is required.
    at ValidationError.inspect (D:\4node\desafios\PF\node_modules\mongoose\lib\error\validation.js:50:26)
    at formatValue (node:internal/util/inspect:806:19)
    at inspect (node:internal/util/inspect:365:10)
    at formatWithOptionsInternal (node:internal/util/inspect:2273:40)
    at Object.format (node:internal/util/inspect:2130:10)
    at basicLayout (D:\4node\desafios\PF\node_modules\log4js\lib\layouts.js:65:52)
    at app (D:\4node\desafios\PF\node_modules\log4js\lib\appenders\file.js:98:23)
    at D:\4node\desafios\PF\node_modules\log4js\lib\log4js.js:43:5
    at Array.forEach (<anonymous>)
    at sendLogEventToAppender (D:\4node\desafios\PF\node_modules\log4js\lib\log4js.js:42:21) {
  errors: {
    email: ValidatorError: Path `email` is required.
        at validate (D:\4node\desafios\PF\node_modules\mongoose\lib\schematype.js:1347:13)
        at SchemaType.doValidate (D:\4node\desafios\PF\node_modules\mongoose\lib\schematype.js:1331:7)
        at D:\4node\desafios\PF\node_modules\mongoose\lib\document.js:2865:18
        at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
      properties: [Object],
      kind: 'required',
      path: 'email',
      value: undefined,
      reason: undefined,
      [Symbol(mongoose:validatorError)]: true
    }
  },
  _message: 'carts validation failed'
}
[2023-05-05T04:01:17.770] [ERROR] errorFile - Error: carts validation failed: email: Path `email` is required.
    at ValidationError.inspect (D:\4node\desafios\PF\node_modules\mongoose\lib\error\validation.js:50:26)
    at formatValue (node:internal/util/inspect:806:19)
    at inspect (node:internal/util/inspect:365:10)
    at formatWithOptionsInternal (node:internal/util/inspect:2273:40)
    at Object.format (node:internal/util/inspect:2130:10)
    at basicLayout (D:\4node\desafios\PF\node_modules\log4js\lib\layouts.js:65:52)
    at app (D:\4node\desafios\PF\node_modules\log4js\lib\appenders\file.js:98:23)
    at D:\4node\desafios\PF\node_modules\log4js\lib\log4js.js:43:5
    at Array.forEach (<anonymous>)
    at sendLogEventToAppender (D:\4node\desafios\PF\node_modules\log4js\lib\log4js.js:42:21) {
  errors: {
    email: ValidatorError: Path `email` is required.
        at validate (D:\4node\desafios\PF\node_modules\mongoose\lib\schematype.js:1347:13)
        at SchemaType.doValidate (D:\4node\desafios\PF\node_modules\mongoose\lib\schematype.js:1331:7)
        at D:\4node\desafios\PF\node_modules\mongoose\lib\document.js:2865:18
        at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
      properties: [Object],
      kind: 'required',
      path: 'email',
      value: undefined,
      reason: undefined,
      [Symbol(mongoose:validatorError)]: true
    }
  },
  _message: 'carts validation failed'
}
